config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'
  post 'customers/download'
  post 'contacts/download'

  resources :contacts
  resources :customers
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer
  max_paginates_per 10

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :contacts
  max_paginates_per 10

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_contacts, only: :download
  before_action :authenticate_admin!

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:customer_id).page params[:page]
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, flash: { success: 'Contact was successfully created.'} }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, flash: { success: 'Contact was successfully updated.'} }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, flash: { success: 'Contact was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  def download
    respond_to do |format|
    format.pdf do
        pdf = ContactPdf.new(@contacts)
        send_data pdf.render, filename: "Relatório de Contatos.pdf",
                              type: "application/pdf",
                              disposition: :inline
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def set_contacts
      @contacts = Contact.order(:customer_id)
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :customer_id)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :set_customers, onle: :download
  before_action :authenticate_admin!

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.order(:name).page params[:page]
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, flash: {success: 'Customer was successfully created.'} }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, flash: {success: 'Customer was successfully updated.'} }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, flash: {success: 'Customer was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  def download
    respond_to do |format|
    format.pdf do
        pdf = CustomerPdf.new(@customers)
        send_data pdf.render, filename: "Relatório de Clientes.pdf",
                              type: "application/pdf",
                              disposition: :inline
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def set_customers
      @customers = Customer.all.order(:id)
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info' }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: 'alert') do
               concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
               concat message
             end)
    end
    nil
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<div class="card card-primary col-sm-12 col-lg-3 font-change">
<%= simple_form_for(@contact) do |f| %>
  <div class="card-header">
    <h1><%= phrase %> <i class="fa fa-pencil" aria-hidden="true"></i></h1>  
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  </div>
  
  <div class="card-body">
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :phone %>
      <%= f.association :customer %>
    </div>
  </div>
  
  <div class="card-footer">
    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-success btn-lg' %>
      <% if show %>
        <%= link_to "Mostrar", @contact,  class: 'btn btn-warning btn-lg' %>
      <% end %>
      <% if back %>
        <%= link_to "Voltar", contacts_path,  class: 'btn btn-secondary btn-lg' %>
      <% end%>
    </div>
  </div>
  <% end %>

</div>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact, phrase: 'Editando contato', show: true, back: true %>

app/views/contacts/index.html.erb
<div class="col-lg-12 table-responsive">
    <div class="row title">
        <h1>Contatos</h1>
        <%= link_to new_contact_path, {class: 'btn btn-02 btn-lg padd'}  do %>
        <i class="fa fa-plus"></i> Novo Contato
        <% end %>
    </div>

    <table class="table table-responsive font-change">
        <thead class="thead-dark">
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Telefone</th>
                <th>Cliente</th>
                <th colspan=" 3">
                    <%= link_to "Relatórios", contacts_download_path(@contacts, format: 'pdf'), method: :post, class: 'btn btn-warning btn-lg', style: 'width: 20rem' %>
                </th>
            </tr>
        </thead>

        <tbody>
            <% @contacts.each do |contact| %>
            <tr>
                <td><%= contact.name %></td>
                <td><%= contact.email %></td>
                <td><%= contact.phone %></td>
                <td><%= contact.customer.name %></td>
                <td><%= link_to 'Mostrar', contact, class: 'btn btn-primary' %></td>
                <td><%= link_to 'Editar', edit_contact_path(contact), class: 'btn btn-warning' %></td>
                <td><%= link_to 'Deletar', contact, method: :delete, class: 'btn btn-danger' ,data: { confirm: 'Tem Certeza?' } %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <%= paginate @contacts %>
</div>
<br>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact, phrase: 'Criando contato', show: false, back: true %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Contato:</h1>
<div class="card col-lg-6 col-sm-12 font-change">
    <div class="card-header">
        <h1><strong>Nome: </strong><%= @contact.name %> - <strong>Email: </strong> <%= @contact.email %> - <strong>Telefone: </strong><%= @contact.phone %></h1>
    </div>
    <div class="card-body">
        <h2>Este contato esta presente na lista de:</h2>
        <hr>
        <%= link_to @contact.customer do %>
          <h3><%= @contact.customer.name %></h3>
        <% end %>
    </div>
    <div class="card-footer">
        <%= link_to 'Editar',edit_contact_path(@contact), class: 'btn btn-warning btn-lg' %>
        <%= link_to 'Voltar', contacts_path, class: 'btn btn-secondary btn-lg' %>
    </div>
</div>

app/views/customers/_form.html.erb
<div class="card card-primary col-sm-12 col-lg-3 font-change">
<%= simple_form_for(@customer) do |f| %>
  <div class="card-header">
    <h1><%= phrase %> <i class="fa fa-pencil" aria-hidden="true"></i></h1>  
    <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  </div>
  
  <div class="card-body">
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :phone %>
      </div>
  </div>
  
  <div class="card-footer">
    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-success btn-lg' %>
      <% if show %>
        <%= link_to "Mostrar", @customer,  class: 'btn btn-warning btn-lg' %>
      <% end %>
      <% if back %>
        <%= link_to "Voltar", customers_path,  class: 'btn btn-secondary btn-lg' %>
      <% end%>
    </div>
  </div>
  <% end %>
</div>

app/views/customers/edit.html.erb
<%= render 'form', contact: @contact, phrase: 'Editando cliente', show: true, back: true %>

app/views/customers/index.html.erb
<div class="col-lg-12 table-responsive">
    <div class="row title">
        <h1>Clientes</h1>
        <%= link_to new_customer_path, {class: 'btn btn-02 btn-lg padd'}  do %>
        <i class="fa fa-plus"></i> Novo Cliente
        <% end %>
    </div>

    <table class="table table-responsive font-change">
        <thead class="thead-dark">
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Telefone</th>
                <th colspan=" 3">
                <%= link_to "Relatórios", customers_download_path(@customers, format: 'pdf'), method: :post, class: 'btn btn-warning btn-lg', style: 'width: 20rem' %>
                </th>
            </tr>
        </thead>

        <tbody>
            <% @customers.each do |customer| %>
            <tr>
                <td><%= customer.name %></td>
                <td><%= customer.email %></td>
                <td><%= customer.phone %></td>
                <td><%= link_to 'Mostrar', customer, class: 'btn btn-primary' %></td>
                <td><%= link_to 'Editar', edit_customer_path(customer), class: 'btn btn-warning' %></td>
                <td><%= link_to 'Deletar', customer, method: :delete, class: 'btn btn-danger' ,data: { confirm: 'Tem Certeza?' } %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <%= paginate @customers %>
</div>
<br>

app/views/customers/new.html.erb
<%= render 'form', contact: @contact, phrase: 'Criando cliente', show: false, back: true %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card col-lg-6 col-sm-12 font-change">
    <div class="card-header">
        <h1><strong>Nome: </strong><%= @customer.name %> - <strong>Email: </strong> <%= @customer.email %> - <strong>Telefone: </strong><%= @customer.phone %></h1>
    </div>
    <div class="card-body">
        <h2>Contatos deste Cliente:</h2>

        <% @customer.contacts.each do |contact| %>
        <hr>
        <ul class="list-group">
          <%= link_to  contact do %>
            <li class="list-group-item">Nome: <%= contact.name %></li>
          <% end %>
            <li class="list-group-item">E-mail: <%= contact.email %></li>
            <li class="list-group-item">Telefone: <%= contact.phone %></li>
        </ul>
        <hr>
        <% end %>
    </div>
    <div class="card-footer">
        <%= link_to 'Editar', edit_customer_path(@customer), class: 'btn btn-warning btn-lg' %>
        <%= link_to 'Voltar', customers_path, class: 'btn btn-secondary btn-lg' %>
    </div>
</div>

app/views/home/index.html.erb
<div class="row content">
    <div class="col-sm-12 col-lg-6">
        <%= image_tag  "workplace.jpg", class: 'home-image' %>
    </div>
    <div class="col-sm-12 col-lg-6">
        <div class="container block-down">
            <div class="jumbotron">
                <h1 class="display-3">O APP criado para organizar a agenda de seus clientes</h1>
                <p class="lead">Criado como prova técnica para vaga de Desenvolvedor na <strong>CustomerX</strong></p>
                <hr class="my-2">
                <p class="lead">
                    <%= link_to customers_path, {class: 'btn btn-02 btn-lg'}  do %>
                    <i class="fa fa-user"></i> Clientes
                    <% end %>
                    <%= link_to contacts_path, {class: 'btn btn-02 btn-lg'}  do %>
                    <i class="fa fa-user"></i> Contatos
                    <% end %>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>FullStackVaga</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&family=PT+Sans+Narrow&display=swap" rel="stylesheet">

</head>

<body>
    <header class="page-header">
        <%= link_to  home_index_path do %>
            <%= image_tag  "RailsNote.png", class: 'logo-image' %>
        <% end %>
        <% if admin_signed_in? %>
            <%= link_to "Sair", destroy_admin_session_path, method: :delete, class: 'btn btn-danger btn-sm' %>
        <% end%>
    </header>
    <%= flash_messages %>
    <%= yield %>
</body>

</html>